/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        facebook: {
          primary: '#1877F2',
          'primary-hover': '#166FE5',
          'primary-light': '#E7F3FF',
          'primary-dark': '#0D5DC9',
          background: '#F0F2F5',
          surface: '#FFFFFF',
          divider: '#DADDE1',
          disabled: '#BCC0C4',
          'text-primary': '#050505',
          'text-secondary': '#65676B',
          'text-placeholder': '#8A8D91',
          success: '#31A24C',
          'success-light': '#E7F5EA',
          warning: '#F7B928',
          'warning-light': '#FFF8E6',
          error: '#F02849',
          'error-light': '#FFEBE9',
        }
      }
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        facebook: {
          "primary": "#1877F2",
          "primary-focus": "#166FE5",
          "primary-content": "#FFFFFF",
          "secondary": "#65676B",
          "secondary-focus": "#050505",
          "secondary-content": "#FFFFFF",
          "accent": "#31A24C",
          "accent-focus": "#248F3D",
          "accent-content": "#FFFFFF",
          "neutral": "#F0F2F5",
          "neutral-focus": "#DADDE1",
          "neutral-content": "#050505",
          "base-100": "#FFFFFF",
          "base-200": "#F0F2F5",
          "base-300": "#DADDE1",
          "base-content": "#050505",
          "info": "#1877F2",
          "success": "#31A24C",
          "warning": "#F7B928",
          "error": "#F02849",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1rem",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
        },
        "facebook-dark": {
          "primary": "#1877F2",
          "primary-focus": "#166FE5",
          "primary-content": "#FFFFFF",
          "secondary": "#B0B3B8",
          "secondary-focus": "#E4E6EB",
          "secondary-content": "#18191A",
          "accent": "#31A24C",
          "accent-focus": "#248F3D",
          "accent-content": "#FFFFFF",
          "neutral": "#242526",
          "neutral-focus": "#3A3B3C",
          "neutral-content": "#E4E6EB",
          "base-100": "#18191A",
          "base-200": "#242526",
          "base-300": "#3A3B3C",
          "base-content": "#E4E6EB",
          "info": "#1877F2",
          "success": "#31A24C",
          "warning": "#F7B928",
          "error": "#F02849",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1rem",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
        }
      }
    ],
  },
}
